Config.Patdown = {
    Enable = true,
    Anims = {
        Executor = {
            lib = "frisk@animation",
            anim = "frisk_clip"
        },
        Victim = {
            car = {
                {
                    lib = "handsonhood@animation",
                    clip = "handsonhood_clip",
                },
                {
                    lib = "handsonhood2@animation",
                    clip = "handsonhood2_clip",
                },
                {
                    lib = "handsonhood3@animation",
                    clip = "handsonhood3_clip",
                }
            },
            nocar = {
                {
                    lib = "handsonhood3@animation",
                    clip = "handsonhood3_clip",
                }
            }
        }
    },
    Check = {
        WeaponWheel=false,
        InventoryItems=true,
        UserInput=false,
    },
    InventoryItems={
        ["WEAPON_PISTOL"]="pistol",
        ["boltcutter"]="melee",
    },
    CategoryTexts={
        ["long_rifle"]=_("patdown.categories.long_rifle","Long Weapon"),
        ["pistol"]=_("patdown.categories.pistol","Small Weapon"),
        ["smg"]=_("patdown.categories.smg","Medium Weapon"),
        ["melee"]=_("patdown.categories.melee","Melee"),
        ["shotgun"]=_("patdown.categories.shotgun","Medium Weapon"),
        ["throwable"]=_("patdown.categories.throwable","Feels like a grenade"),
        ["other"]=_("patdown.categories.other","Something unknown"),
        ["heavy_weapon"]=_("patdown.categories.heavy_weapon","Arsenal"),
    },
    WeaponsList = {
        ["weapon_advancedrifle"]="long_rifle",
        ["weapon_appistol"]="pistol",
        ["weapon_assaultrifle"]="long_rifle",
        ["weapon_assaultrifle_mk2"]="long_rifle",
        ["weapon_assaultshotgun"]="shotgun",
        ["weapon_assaultsmg"]="smg",
        ["weapon_autoshotgun"]="shotgun",
        ["weapon_bat"]="melee",
        ["weapon_ball"]="throwable",
        ["weapon_battleaxe"]="melee",
        ["weapon_bottle"]="melee",
        ["weapon_bullpuprifle"]="long_rifle",
        ["weapon_bullpuprifle_mk2"]="long_rifle",
        ["weapon_bullpupshotgun"]="shotgun",
        ["weapon_bzgas"]="throwable",
        ["weapon_carbinerifle"]="long_rifle",
        ["weapon_carbinerifle_mk2"]="long_rifle",
        ["weapon_combatmg"]="long_rifle",
        ["weapon_combatmg_mk2"]="long_rifle",
        ["weapon_combatpdw"]="smg",
        ["weapon_combatpistol"]="pistol",
        ["weapon_compactlauncher"]="heavy_weapon",
        ["weapon_compactrifle"]="long_rifle",
        ["weapon_crowbar"]="melee",
        ["weapon_dagger"]="melee",
        ["weapon_dbshotgun"]="shotgun",
        ["weapon_doubleaction"]="pistol",
        ["weapon_fireextinguisher"]="other",
        ["weapon_firework"]="heavy_weapon",
        ["weapon_flare"]="throwable",
        ["weapon_flaregun"]="pistol",
        ["weapon_flashlight"]="melee",
        ["weapon_golfclub"]="melee",
        ["weapon_grenade"]="throwable",
        ["weapon_grenadelauncher"]="heavy_weapon",
        ["weapon_gusenberg"]="long_rifle",
        ["weapon_hammer"]="melee",
        ["weapon_hatchet"]="melee",
        ["weapon_heavypistol"]="pistol",
        ["weapon_heavyshotgun"]="shotgun",
        ["weapon_heavysniper"]="long_rifle",
        ["weapon_heavysniper_mk2"]="long_rifle",
        ["weapon_hominglauncher"]="heavy_weapon",
        ["weapon_knife"]="melee",
        ["weapon_knuckle"]="melee",
        ["weapon_machete"]="melee",
        ["weapon_machinepistol"]="pistol",
        ["weapon_marksmanpistol"]="smg",
        ["weapon_marksmanrifle"]="long_rifle",
        ["weapon_marksmanrifle_mk2"]="long_rifle",
        ["weapon_mg"]="long_rifle",
        ["weapon_microsmg"]="smg",
        ["weapon_minigun"]="heavy_weapon",
        ["weapon_minismg"]="smg",
        ["weapon_molotov"]="throwable",
        ["weapon_musket"]="shotgun",
        ["weapon_nightstick"]="melee",
        ["weapon_petrolcan"]="other",
        ["weapon_pipebomb"]="throwable",
        ["weapon_pistol"]="pistol",
        ["weapon_pistol50"]="pistol",
        ["weapon_pistol_mk2"]="pistol",
        ["weapon_poolcue"]="melee",
        ["weapon_proxmine"]="throwable",
        ["weapon_pumpshotgun"]="shotgun",
        ["weapon_pumpshotgun_mk2"]="shotgun",
        ["weapon_railgun"]="heavy_weapon",
        ["weapon_revolver"]="pistol",
        ["weapon_revolver_mk2"]="pistol",
        ["weapon_rpg"]="heavy_weapon",
        ["weapon_sawnoffshotgun"]="shotgun",
        ["weapon_smg"]="smg",
        ["weapon_smg_mk2"]="smg",
        ["weapon_smokegrenade"]="throwable",
        ["weapon_sniperrifle"]="long_rifle",
        ["weapon_snowball"]="throwable",
        ["weapon_snspistol"]="pistol",
        ["weapon_snspistol_mk2"]="pistol",
        ["weapon_specialcarbine"]="long_rifle",
        ["weapon_specialcarbine_mk2"]="long_rifle",
        ["weapon_stickybomb"]="throwable",
        ["weapon_stungun"]="other",
        ["weapon_switchblade"]="melee",
        ["weapon_vintagepistol"]="pistol",
        ["weapon_wrench"]="melee",
        ["weapon_raypistol"]="pistol",
        ["weapon_raycarbine"]="long_rifle",
        ["weapon_rayminigun"]="heavy_weapon",
        ["weapon_stone_hatchet"]="melee",
    },
    UserInputMaxItems=5,
};
